import { ClerkProvider } from "@clerk/nextjs";
import type { Metadata } from "next";
import { Open_Sans } from "next/font/google";
import "~/app/globals.css";
import { ThemeProvider } from "~/modules/common/components/theme/ThemeProvider";
import { cn } from "~/modules/common/utils/utils";
import ModalProvider from "~/modules/servers/components/modal/ModalProvider";

const font = Open_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Team Chat Application",
  description: "Generated by create next app",
};

type RootLayoutProps = { children: React.ReactNode };
export default function RootLayout(props: RootLayoutProps) {
  const { children } = props;

  return (
    <ClerkProvider>
      <html lang="en" suppressHydrationWarning>
        <body className={cn(font.className, "bg-white dark:bg-[#313338]")}>
          <ThemeProvider
            attribute="class"
            defaultTheme="dark"
            enableSystem={true}
            storageKey="discord-theme"
          >
            <ModalProvider />
            {children}
          </ThemeProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
